// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, Fragment, jsxs } from 'react/jsx-runtime';
import React from 'react';
import { Link, Text, AppPlaceholder, RichText, NextImage } from '@sitecore-content-sdk/nextjs';
import { toJsonLdString } from 'src/lib/structured-data/jsonld';
import componentMap from '.sitecore/component-map';
import StructuredData from 'components/structured-data/StructuredData';
import { buildProductJsonLd, buildArticleJsonLd } from 'src/lib/structured-data/schema';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'Fragment', value: Fragment },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
    ]
  },
  {
    module: 'src/lib/structured-data/jsonld',
    exports: [
      { name: 'toJsonLdString', value: toJsonLdString },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'components/structured-data/StructuredData',
    exports: [
      { name: 'default', value: StructuredData },
    ]
  },
  {
    module: 'src/lib/structured-data/schema',
    exports: [
      { name: 'buildProductJsonLd', value: buildProductJsonLd },
      { name: 'buildArticleJsonLd', value: buildArticleJsonLd },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
