'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { useState, Fragment as Fragment_9e46adc109100050462083db825547fcdce28feb, useEffect } from 'react';
import React from 'react';
import { Link, Text, useSitecore, CdpHelper, RichText, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'Fragment', value: Fragment_9e46adc109100050462083db825547fcdce28feb },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'RichText', value: RichText },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
