name: CI-CD - PUBLIC WEBSITE (PREVIEW)
on: 
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/PR_PREVIEW.yml
      - .github/workflows/build_deploy_preview.yml
      - .github/actions/setup-node-nexus/**
      - .github/actions/setup-nexus-npm/**
      - 'apps/sitecore-rendering/**'
      - 'packages/ui/**'
      - 'vercel.json'
      - 'package.json'
      - 'package-lock.json'
      - '.npmrc'
      - '.nvmrc'

permissions:
  contents: read
  pull-requests: write

jobs:
  build-public-site:
    uses: ./.github/workflows/build_deploy_preview.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      NEXUS_NPM_AUTH: ${{ secrets.NEXUS_NPM_AUTH }}
      SITECORE_EDGE_CONTEXT_ID: ${{ secrets.DEV_SITECORE_EDGE_CONTEXT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.RENDERING_VERCEL_PROJECT_ID }}
      VERCEL_PROTECTION_BYPASS: ${{ secrets.RENDERING_VERCEL_PROTECTION_BYPASS }}
